# Generated by Django 4.0.5 on 2022-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(default=0, upload_to='movies/', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
