# Generated by Django 4.0.5 on 2022-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.SlugField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
